/* version 3.1.0 $Id$ */
 
DROP TABLE IF EXISTS `#__imprints_imprints`;
DROP TABLE IF EXISTS `#__imprints_remarks`;

CREATE  TABLE IF NOT EXISTS `#__imprint_imprints` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(255) NOT NULL DEFAULT '' ,
  `default` TINYINT NOT NULL DEFAULT 0 ,
  `firma` VARCHAR(255) NOT NULL DEFAULT '' ,
  `name1` VARCHAR(255) NOT NULL DEFAULT '' ,
  `name2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `name3` VARCHAR(255) NOT NULL DEFAULT '' ,
  `name4` VARCHAR(255) NOT NULL DEFAULT '' ,
  `street` VARCHAR(255) NOT NULL DEFAULT '' ,
  `zipcode` VARCHAR(255) NOT NULL DEFAULT '' ,
  `city` VARCHAR(255) NOT NULL DEFAULT '' ,
  `country` VARCHAR(255) NOT NULL DEFAULT '' ,
  `telephone` VARCHAR(255) NOT NULL DEFAULT '' ,
  `fax` VARCHAR(255) NOT NULL DEFAULT '' ,
  `mobilephone` VARCHAR(255) NOT NULL DEFAULT '' ,
  `website` VARCHAR(255) NOT NULL DEFAULT '' ,
  `email` VARCHAR(255) NOT NULL DEFAULT '' ,
  `account_holder` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_code` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_name` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_number` VARCHAR(255) NOT NULL DEFAULT '' ,
  `iban` VARCHAR(255) NOT NULL DEFAULT '' ,
  `swift` VARCHAR(255) NOT NULL DEFAULT '' ,
  `account_holder2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_code2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bankname2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_number2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `iban2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `swift2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `account_holder3` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_code3` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_name3` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_number3` VARCHAR(255) NOT NULL DEFAULT '' ,
  `iban3` VARCHAR(255) NOT NULL DEFAULT '' ,
  `swift3` VARCHAR(255) NOT NULL DEFAULT '' ,
  `account_holder4` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_code4` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_name4` VARCHAR(255) NOT NULL DEFAULT '' ,
  `bank_number4` VARCHAR(255) NOT NULL DEFAULT '' ,
  `iban4` VARCHAR(255) NOT NULL DEFAULT '' ,
  `swift4` VARCHAR(255) NOT NULL DEFAULT '' ,
  `vertretertitel` VARCHAR(255) NOT NULL DEFAULT 'Vertretungsberechtigt' ,
  `vertreter` VARCHAR(255) NOT NULL DEFAULT '' ,
  `vertreteremail` VARCHAR(255) NOT NULL DEFAULT '' ,
  `registergericht` VARCHAR(255) NOT NULL DEFAULT '' ,
  `registernummer` VARCHAR(255) NOT NULL DEFAULT '' ,
  `sales_tax_id` VARCHAR(255) NOT NULL DEFAULT '' ,
  `economic_id` VARCHAR(255) NOT NULL DEFAULT '' ,
  `responsible_for_content` VARCHAR(255) NOT NULL DEFAULT '' ,
  `inhaltemail` VARCHAR(255) NOT NULL DEFAULT '' ,
  `recht2grund` VARCHAR(255) NOT NULL DEFAULT '' ,
  `vertretertitel2` VARCHAR(255) NOT NULL DEFAULT 'Vertretungsberechtigt' ,
  `vertreter2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `vertreteremail2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `registergericht2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `registernummer2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `ustidnr2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `wirtidnr2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `inhaltperson2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `inhaltemail2` VARCHAR(255) NOT NULL DEFAULT '' ,
  `technikperson` VARCHAR(255) NOT NULL DEFAULT '' ,
  `technikwebsite` VARCHAR(255) NOT NULL DEFAULT '' ,
  `technikemail` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra1titel` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra1person` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra1website` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra1email` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra2titel` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra2person` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra2website` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra2email` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra3titel` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra3person` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra3website` VARCHAR(255) NOT NULL DEFAULT '' ,
  `extra3email` VARCHAR(255) NOT NULL DEFAULT '' ,
  `template_name` VARCHAR(255) NOT NULL DEFAULT '' ,
  `template_creator` VARCHAR(255) NOT NULL DEFAULT '' ,
  `templatewebsite` VARCHAR(255) NOT NULL DEFAULT '' ,
  `template_creator_email` VARCHAR(255) NOT NULL DEFAULT '' ,
  `contacturl` VARCHAR(255) NOT NULL DEFAULT '' ,
  `agburl` VARCHAR(255) NOT NULL DEFAULT '' ,
  `image` VARCHAR(255) NOT NULL DEFAULT '' ,
  `misc` TEXT NOT NULL ,
  `params` TEXT NOT NULL ,
  `remarks` TEXT NOT NULL ,
  `image_rights` TEXT NOT NULL ,
  `image_sources` TEXT NOT NULL ,
  `adresstitel` VARCHAR(255) NOT NULL DEFAULT 'Anbieterinformationen' ,
  `datenschutztitel` VARCHAR(255) NOT NULL DEFAULT '' ,
  PRIMARY KEY (`id`) )
  COMMENT='Saves the different imprints'
ENGINE = InnoDB;

CREATE  TABLE IF NOT EXISTS `#__imprint_remarks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `name` VARCHAR(255) NOT NULL ,
  `text` TEXT NOT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;

insert into `#__imprint_imprints`(`id`,`name`,`default`,`misc`) values ( '1', 'Standard', '1', 'Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.\n\nAlle hier verwendeten Namen, Begriffe, Zeichen und Grafiken können Marken- oder Warenzeichen im Besitze ihrer rechtlichen Eigentümer sein. Die Rechte aller erwähnten und benutzten Marken- und Warenzeichen liegen ausschließlich bei deren Besitzern.' );
