/* version 3.0.1 $Id$ */
 
DROP TABLE IF EXISTS `#__impressum`;

CREATE TABLE `#__impressum` (                                                                           
                 `id` int(11) NOT NULL auto_increment,    
                 `name` varchar(255) NOT NULL default '',
                 `default` tinyint NOT NULL default 0,                                                              
                 `firma` varchar(255) NOT NULL default '',               
                 `name1` varchar(255) NOT NULL default '',               
                 `name2` varchar(255) NOT NULL default '',               
                 `name3` varchar(255) NOT NULL default '',               
                 `name4` varchar(255) NOT NULL default '',               
                 `strasse` varchar(255) NOT NULL default '',             
                 `plz` varchar(255) NOT NULL default '',                 
                 `ort` varchar(255) NOT NULL default '',                 
                 `land` varchar(255) NOT NULL default '',                
                 `telefon` varchar(255) NOT NULL default '',             
                 `fax` varchar(255) NOT NULL default '',                 
                 `handy` varchar(255) NOT NULL default '',               
                 `website` varchar(255) NOT NULL default '',             
                 `email` varchar(255) NOT NULL default '',
                 `bankinhaber` varchar(255) NOT NULL default '',            
                 `blz` varchar(255) NOT NULL default '',                 
                 `bankname` varchar(255) NOT NULL default '',            
                 `kontonr` varchar(255) NOT NULL default '',             
                 `iban` varchar(255) NOT NULL default '',                
                 `swift` varchar(255) NOT NULL default '',
                 `bankinhaber2` varchar(255) NOT NULL default '',                  
                 `blz2` varchar(255) NOT NULL default '',                 
                 `bankname2` varchar(255) NOT NULL default '',            
                 `kontonr2` varchar(255) NOT NULL default '',             
                 `iban2` varchar(255) NOT NULL default '',                
                 `swift2` varchar(255) NOT NULL default '',
                 `bankinhaber3` varchar(255) NOT NULL default '',                  
                 `blz3` varchar(255) NOT NULL default '',                 
                 `bankname3` varchar(255) NOT NULL default '',            
                 `kontonr3` varchar(255) NOT NULL default '',             
                 `iban3` varchar(255) NOT NULL default '',                
                 `swift3` varchar(255) NOT NULL default '',   
                 `bankinhaber4` varchar(255) NOT NULL default '',                  
                 `blz4` varchar(255) NOT NULL default '',                 
                 `bankname4` varchar(255) NOT NULL default '',            
                 `kontonr4` varchar(255) NOT NULL default '',             
                 `iban4` varchar(255) NOT NULL default '',                
                 `swift4` varchar(255) NOT NULL default '',
                 `vertretertitel` varchar(255) NOT NULL default 'Vertretungsberechtigt',                                                                                                     
                 `vertreter` varchar(255) NOT NULL default '',   
                 `vertreteremail` varchar(255) NOT NULL default '',         
                 `registergericht` varchar(255) NOT NULL default '',     
                 `registernummer` varchar(255) NOT NULL default '',      
                 `ustidnr` varchar(255) NOT NULL default '',   
                 `wirtidnr` varchar(255) NOT NULL default '', 
                 `inhaltperson` varchar(255) NOT NULL default '',        
                 `inhaltemail` varchar(255) NOT NULL default '',  
                 `recht2grund` varchar(255) NOT NULL default '',
                 `vertretertitel2` varchar(255) NOT NULL default 'Vertretungsberechtigt',                                       
                 `vertreter2` varchar(255) NOT NULL default '',   
                 `vertreteremail2` varchar(255) NOT NULL default '',         
                 `registergericht2` varchar(255) NOT NULL default '',     
                 `registernummer2` varchar(255) NOT NULL default '',      
                 `ustidnr2` varchar(255) NOT NULL default '',   
                 `wirtidnr2` varchar(255) NOT NULL default '',    
                 `inhaltperson2` varchar(255) NOT NULL default '',        
                 `inhaltemail2` varchar(255) NOT NULL default '',                                    
                 `technikperson` varchar(255) NOT NULL default '',       
                 `technikwebsite` varchar(255) NOT NULL default '',      
                 `technikemail` varchar(255) NOT NULL default '', 
                 `extra1titel` varchar(255) NOT NULL default '',       
                 `extra1person` varchar(255) NOT NULL default '', 
                 `extra1website` varchar(255) NOT NULL default '',      
                 `extra1email` varchar(255) NOT NULL default '',  
                 `extra2titel` varchar(255) NOT NULL default '',   
                 `extra2person` varchar(255) NOT NULL default '', 
                 `extra2website` varchar(255) NOT NULL default '',      
                 `extra2email` varchar(255) NOT NULL default '',     
                 `extra3titel` varchar(255) NOT NULL default '',
                 `extra3person` varchar(255) NOT NULL default '',
                 `extra3website` varchar(255) NOT NULL default '',      
                 `extra3email` varchar(255) NOT NULL default '',     
                 `templatename` varchar(255) NOT NULL default '',        
                 `templatehersteller` varchar(255) NOT NULL default '',  
                 `templatewebsite` varchar(255) NOT NULL default '',
                 `templateemail` varchar(255) NOT NULL default '',
                 `contacturl` varchar(255) NOT NULL default '',   
                 `agburl` varchar(255) NOT NULL default '',                                                 
                 `image` varchar(255) NOT NULL default '',               
                 `misc` text NOT NULL,                                   
                 `params` text NOT NULL,                                 
                 `bildrechte` text NOT NULL,                             
                 `bildquellen` text NOT NULL,                            
                 `adresstitel` varchar(255) NOT NULL default 'Anbieterinformationen',  
                 `datenschutztitel` varchar(255) NOT NULL default '',                 
                 PRIMARY KEY  (`id`)                                                                                    
               )   
;
insert into `#__impressum`(`id`,`name`,`default`,`misc`) values ( '1','Standard','1','Trotz sorgf&auml;ltiger inhaltlicher Kontrolle &uuml;bernehmen wir keine Haftung f&uuml;r die Inhalte externer Links. F&uuml;r den Inhalt der verlinkten Seiten sind ausschlie&szlig;lich deren Betreiber verantwortlich.<br /><br />Alle hier verwendeten Namen, Begriffe, Zeichen und Grafiken k&ouml;nnen Marken- oder Warenzeichen im Besitze ihrer rechtlichen Eigent&uuml;mer sein. Die Rechte aller erw&auml;hnten und benutzten Marken- und Warenzeichen liegen ausschlie&szlig;lich bei deren Besitzern.');
                 